package gitops

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Lance52259/doc-draft/internal/model"
)

// PRBodyInput fills templates/pr_body.md placeholders.
type PRBodyInput struct {
	Practice model.Practice
	Result   *model.GenerateResult
	BRepo    string
	BSHA     string
	SkillID  string
	Template string // optional override of raw template content
}

// BuildPRBody renders the universal PR description template.
func BuildPRBody(in PRBodyInput) string {
	tpl := strings.TrimSpace(in.Template)
	if tpl == "" {
		tpl = defaultPRBodyTemplate()
	}

	service := in.Practice.Service()
	if service == "" {
		service = "unknown"
	}
	simple := in.Practice.SimpleTitle()
	practiceID := in.Practice.PracticeID
	if practiceID == "" && in.Result != nil {
		practiceID = in.Result.PracticeID
	}
	bSHA := in.BSHA
	if bSHA == "" {
		bSHA = "unknown"
	}
	skill := in.SkillID
	if skill == "" {
		skill = "best-practice-doc"
	}
	summary := ""
	if in.Result != nil {
		summary = strings.TrimSpace(in.Result.Summary)
	}
	if summary == "" {
		summary = fmt.Sprintf("Add/update best-practice docs and navigation for %s (%s).", service, simple)
	}

	var files strings.Builder
	if in.Result != nil && len(in.Result.Files) > 0 {
		for _, f := range in.Result.Files {
			fmt.Fprintf(&files, "- `%s` `%s`\n", f.Action, f.Path)
		}
	} else {
		files.WriteString("- (no files)\n")
	}

	replacer := strings.NewReplacer(
		"{service}", service,
		"{simple_title}", simple,
		"{practice_id}", practiceID,
		"{b_repo}", in.BRepo,
		"{b_sha}", bSHA,
		"{skill_id}", skill,
		"{ai_summary}", summary,
		"{file_list}", strings.TrimRight(files.String(), "\n"),
	)
	out := replacer.Replace(tpl)
	if !strings.HasSuffix(out, "\n") {
		out += "\n"
	}
	return out
}

// LoadPRBodyTemplate reads templates/pr_body.md from repo root when present.
func LoadPRBodyTemplate(repoRoot string) (string, error) {
	path := filepath.Join(repoRoot, "templates", "pr_body.md")
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return string(data), nil
}

// SummarizeChanges is kept for callers; prefer BuildPRBody with Practice context.
func SummarizeChanges(result *model.GenerateResult, bRepo, bSHA string) string {
	p := model.Practice{PracticeID: result.PracticeID, SourcePath: result.PracticeID}
	return BuildPRBody(PRBodyInput{Practice: p, Result: result, BRepo: bRepo, BSHA: bSHA})
}

func defaultPRBodyTemplate() string {
	// Keep in sync with templates/pr_body.md (fallback when file is unavailable).
	code := func(s string) string { return "`" + s + "`" }
	var b strings.Builder
	b.WriteString("## Summary\n\n")
	b.WriteString("This PR is auto-generated by **doc-craft** to sync a best-practice example from repo B into Chinese docs in repo C (hcbp-demo).\n\n")
	b.WriteString("| Item | Value |\n|------|-------|\n")
	b.WriteString("| Service | " + code("{service}") + " |\n")
	b.WriteString("| Practice | " + code("{simple_title}") + " |\n")
	b.WriteString("| Source practice ID | " + code("{practice_id}") + " |\n")
	b.WriteString("| Source repo | " + code("{b_repo}@{b_sha}") + " |\n")
	b.WriteString("| Generator | Skill " + code("{skill_id}") + " + DeepSeek |\n\n")
	b.WriteString("## Motivation\n\n")
	b.WriteString("A new best practice appeared under B repo `examples/` that is not yet covered in this repository. The change adds the practice body per hcbp-demo conventions and updates navigation (`index.md` / `SUMMARY.md`, plus `README.md` when the service is new).\n\n")
	b.WriteString("## Changes\n\n{ai_summary}\n\n### Files\n\n{file_list}\n\n")
	b.WriteString("## Review checklist\n\n")
	b.WriteString("### Document structure (Skill / template)\n\n")
	b.WriteString("- [ ] Chinese body: `docs/zh-cn/best-practices/{service}/{practice}.md`\n")
	b.WriteString("- [ ] English body: `docs/en-us/best-practices/{service}/{practice}.md`\n")
	b.WriteString("- [ ] Required sections present in both locales; HCL matches source scripts\n")
	b.WriteString("- [ ] No real AK/SK/passwords (placeholders are OK)\n\n")
	b.WriteString("### Navigation and index (EN first, then ZH follows EN order)\n\n")
	b.WriteString("- [ ] Updated EN `index.md` / `SUMMARY.md` (and README if new service)\n")
	b.WriteString("- [ ] Updated ZH `index.md` / `SUMMARY.md` (and README if new service) aligned with EN order\n")
	b.WriteString("- [ ] No destructive rewrite of either `SUMMARY.md`\n\n")
	b.WriteString("### Before merge\n\n")
	b.WriteString("- [ ] Title matches: `docs({service}): support new best practice for {simple title}`\n")
	b.WriteString("- [ ] Spot-check command blocks and dependency tree\n")
	b.WriteString("- [ ] Merge when ready; after merge this practice is considered synced\n\n")
	b.WriteString("---\n\n")
	b.WriteString("*Generated by [doc-craft](https://github.com/Lance52259/doc-draft). Please review before merge.*\n")
	return b.String()
}
