package gitops

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Lance52259/doc-draft/internal/model"
)

// PRBodyInput fills templates/pr_body.md placeholders.
type PRBodyInput struct {
	Practice model.Practice
	Result   *model.GenerateResult
	BRepo    string
	BSHA     string
	SkillID  string
	Template string // optional override of raw template content
}

// BuildPRBody renders the universal PR description template.
func BuildPRBody(in PRBodyInput) string {
	tpl := strings.TrimSpace(in.Template)
	if tpl == "" {
		tpl = defaultPRBodyTemplate()
	}

	service := in.Practice.Service()
	if service == "" {
		service = "unknown"
	}
	simple := in.Practice.SimpleTitle()
	practiceID := in.Practice.PracticeID
	if practiceID == "" && in.Result != nil {
		practiceID = in.Result.PracticeID
	}
	bSHA := in.BSHA
	if bSHA == "" {
		bSHA = "unknown"
	}
	skill := in.SkillID
	if skill == "" {
		skill = "best-practice-doc"
	}
	summary := ""
	if in.Result != nil {
		summary = strings.TrimSpace(in.Result.Summary)
	}
	if summary == "" {
		summary = fmt.Sprintf("新增/更新 %s（%s）相关最佳实践文档与导航。", service, simple)
	}

	var files strings.Builder
	if in.Result != nil && len(in.Result.Files) > 0 {
		for _, f := range in.Result.Files {
			fmt.Fprintf(&files, "- `%s` `%s`\n", f.Action, f.Path)
		}
	} else {
		files.WriteString("- (无文件列表)\n")
	}

	replacer := strings.NewReplacer(
		"{service}", service,
		"{simple_title}", simple,
		"{practice_id}", practiceID,
		"{b_repo}", in.BRepo,
		"{b_sha}", bSHA,
		"{skill_id}", skill,
		"{ai_summary}", summary,
		"{file_list}", strings.TrimRight(files.String(), "\n"),
	)
	out := replacer.Replace(tpl)
	if !strings.HasSuffix(out, "\n") {
		out += "\n"
	}
	return out
}

// LoadPRBodyTemplate reads templates/pr_body.md from repo root when present.
func LoadPRBodyTemplate(repoRoot string) (string, error) {
	path := filepath.Join(repoRoot, "templates", "pr_body.md")
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return string(data), nil
}

// SummarizeChanges is kept for callers; prefer BuildPRBody with Practice context.
func SummarizeChanges(result *model.GenerateResult, bRepo, bSHA string) string {
	p := model.Practice{PracticeID: result.PracticeID, SourcePath: result.PracticeID}
	return BuildPRBody(PRBodyInput{Practice: p, Result: result, BRepo: bRepo, BSHA: bSHA})
}

func defaultPRBodyTemplate() string {
	// Keep in sync with templates/pr_body.md (fallback when file is unavailable).
	code := func(s string) string { return "`" + s + "`" }
	var b strings.Builder
	b.WriteString("## Summary\n\n")
	b.WriteString("本 PR 由 **doc-craft** 自动生成，用于将 B 仓最佳实践示例同步为 C 仓（hcbp-demo）中文文档。\n\n")
	b.WriteString("| 项 | 内容 |\n|----|------|\n")
	b.WriteString("| 服务 | " + code("{service}") + " |\n")
	b.WriteString("| 实践 | " + code("{simple_title}") + " |\n")
	b.WriteString("| 源实践 ID | " + code("{practice_id}") + " |\n")
	b.WriteString("| 源仓库 | " + code("{b_repo}@{b_sha}") + " |\n")
	b.WriteString("| 生成方式 | Skill " + code("{skill_id}") + " + DeepSeek |\n\n")
	b.WriteString("## Motivation\n\n")
	b.WriteString("B 仓 `examples/` 下出现尚未对接至本仓库的最佳实践，需按 hcbp-demo 文档规范补充正文，并同步更新导航（`index.md` / `SUMMARY.md`，新服务时含 `README.md`）。\n\n")
	b.WriteString("## Changes\n\n{ai_summary}\n\n### Files\n\n{file_list}\n\n")
	b.WriteString("## Review checklist\n\n")
	b.WriteString("### 文档结构（对齐 Skill / 模板）\n\n")
	b.WriteString("- [ ] 正文路径为 `docs/zh-cn/best-practices/{service}/{practice}.md`\n")
	b.WriteString("- [ ] 固定章节齐全：应用场景、相关资源/数据源、操作步骤、参考信息\n")
	b.WriteString("- [ ] HCL 与参数说明来自源脚本，无臆造资源/参数\n")
	b.WriteString("- [ ] 无真实 AK/SK/密码等敏感信息（占位符可接受）\n\n")
	b.WriteString("### 导航与索引\n\n")
	b.WriteString("- [ ] 已更新（或确认无需更新）`docs/zh-cn/best-practices/{service}/index.md` 最佳实践列表（文件名升序）\n")
	b.WriteString("- [ ] 已更新 `docs/zh-cn/SUMMARY.md`\n")
	b.WriteString("- [ ] 若为新服务：已新增 `index.md`，并更新 `docs/zh-cn/best-practices/README.md` 文档导航\n\n")
	b.WriteString("### 合并前\n\n")
	b.WriteString("- [ ] 标题符合：`docs({service}): support new best practice for {simple title}`\n")
	b.WriteString("- [ ] 人工抽检命令块与依赖关系树\n")
	b.WriteString("- [ ] 确认无误后合并；合并后该实践视为已对接\n\n")
	b.WriteString("---\n\n")
	b.WriteString("*Generated by [doc-craft](https://github.com/Lance52259/doc-draft). Please review before merge.*\n")
	return b.String()
}
